---
# Alternative to this:
#   manually generate and copy/paste the certificate & private key into the
#   Authelia configuration.
#
#   Generation possibilities:
#
#     - using Authelia (in docker, from https://is.gd/MAgu03):
#       podman run --rm authelia/authelia sh -c "authelia crypto certificate rsa generate --common-name authelia.example.com && cat public.crt && cat private.pem"
#
#     - using openssl:
#       TBD
#

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: authelia-local-cert-private-key
  namespace: authelia-local
  labels:
    {{- include "managed-objects.labels" . | nindent 4 }}
spec:
  secretName: authelia-local-cert-private-key

  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048

  duration: 2160h # 90d
  renewBefore: 360h # 15d

  usages:
    - server auth
    - client auth

  subject:
    organizations:
      - flypenguin.de

  commonName: auth-local.localhost.traefik.me

  #uris:
  #  - spiffe://cluster.local/ns/sandbox/sa/example

  issuerRef:
    name: internal-ca
    kind: ClusterIssuer
