---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned
  namespace: cert-manger
  labels:
    {{- include "managed-objects.labels" . | nindent 4 }}
spec:
  selfSigned: {}
