apiVersion: generators.external-secrets.io/v1alpha1
kind: ClusterGenerator
metadata:
  name: alnum-upper
  labels:
    {{- include "managed-objects.labels" . | nindent 4 }}
spec:
  kind: Password
  generator:
    passwordSpec:
      length: 42
      digits: 5
      symbols: 0
      noUpper: false
      allowRepeat: true
