---
apiVersion: "traefik.io/v1alpha1"
kind: "Middleware"
metadata:
  name: {{ .Values.traefik.forwardMiddlewareName }}
  namespace: {{ .Values.traefik.namespace }}
  labels:
    {{- include "managed-objects.labels" . | nindent 4 }}
    app.kubernetes.io/instance: "dex"
    app.kubernetes.io/name: "dex"
spec:
  forwardAuth:
    address: "http://dex.dex.svc.cluster.local:5556/"
    trustForwardHeader: true
    authResponseHeaders:
      - X-Forwarded-User
      - X-Forwarded-Email
