rbac:
  enabled: true

ingress:
  enabled: true
  # annotations: { cert-manager.io/cluster-issuer: playground-ca }
  certManager: true
  tls:
    enabled: true
    secret: "tls-me-traefik-localhost-auth"
  gatewayAPI:
    enabled: false
  traefikCRD:
    enabled: false
    disableIngressRoute: false
    middlewares:
      auth:
        nameOverride: ""
        endpointOverride: ""
        authResponseHeaders:
          - "Remote-User"
          - "Remote-Name"
          - "Remote-Email"
          - "Remote-Groups"

pod:
  extraVolumes:
    - name: users-database
      secret:
        secretName: authelia-users-database
        optional: false
    - # to read the "email" notifications
      name: authelia-notifications
      emptyDir: {}

  env:
    - # https://is.gd/v9hRop
      # enabled templating ...
      name: X_AUTHELIA_CONFIG_FILTERS
      value: "template"
    - # https://is.gd/yHegFy -- authelia go templating reference
      # adds an ENV var from a secret. see "configMap.identityProviders.hmac" below.
      name: HMAC_VALUE
      valueFrom:
        secretKeyRef:
          name: authelia-hmac-value
          key: hmac

  extraVolumeMounts:
    - name: users-database
      mountPath: /config/users_database.yml
      readOnly: true
      subPath: users_database.yml
    - name: authelia-notifications
      mountPath: /authelia-notifications

  extraContainers:
    - # to read the "email" notifications
      name: filemanager
      image: filebrowser/filebrowser
      args: ["-p", "28080", "--noauth", "-r", "/authelia-notifications"]
      securityContext:
        runAsUser: 0
      ports:
        - containerPort: 28080
          name: filemanager
      volumeMounts:
        - name: authelia-notifications
          mountPath: /authelia-notifications

configMap:
  authentication_backend:
    refresh_interval: always
    file:
      enabled: true
      watch: true
      search:
        email: true
        case_insensitive: false
    password_change:
      disable: false
    password_reset:
      disable: false

  identity_providers:
    oidc:
      # THIS DOCUMENTATION IS INCOMPLETE: https://is.gd/o84ZFQ
      # refer to the example values.yaml !!
      hmac_secret:
        # WE generate this secret, and it now must be added to "secrets.additionalSecrets" below.
        # otherwise deployment fails with an error message.
        disabled: true
        secret_name: "authelia-hmac-value"
        path: hmac

  notifier:
    filesystem:
      enabled: true
      filename: /authelia-notifications/notification.txt

  password_policy:
    zxcvbn:
      enabled: true
      min_score: 3

  session:
    cookies:
      - domain: localhost.traefik.me
        subdomain: auth

  storage:
    postgres:
      enabled: true
      deploy: true
      address: "tcp://authelia-postgresql.authelia.svc.cluster.local:5432"
      database: "authelia"
      schema: "public"
      username: "authelia"
      password:
        secret_name: ~
        value: "authelia"
        path: "storage.postgres.password.txt"

postgresql:
  # default values, but here to see how we configure this.
  auth:
    postgresPassword: authelia
    username: authelia
    password: authelia
    database: authelia

secret:
  additionalSecrets:
    authelia-hmac-value:
      path: ""
      items:
        - key: hmac
