---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: internal-ca
  namespace: cert-manager
spec:
  secretName: internal-ca-cert

  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048

  isCA: true
  usages:
    - server auth
    - client auth

  emailAddresses:
    - penguin@flypenguin.eu
  subject:
    organizations:
      - OAuth Test Playground

  commonName: internal-ca

  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
