#cloud-config

---
write-files:
  - path: /etc/consul/consul.json
    permissions: '0644'
    content: |
      {
          "data_dir": "/var/lib/consul/data",
          "log_level": "INFO",
          "server": true,
          "disable_update_check": true,
          "client_addr": "$private_ipv4",
          "ports": {
            "dns": 53
          },
          "recursor": "8.8.8.8"
      }
  - path: /etc/nomad/client.hcl
    permissions: '0644'
    content: |
      log_level = "DEBUG"
      data_dir = "/tmp/nomad"
      bind_addr = "$private_ipv4"
      client {
          enabled = true
          network_interface = "eth1"
          servers = ["__MASTER_IP__:4647"]
      }
      consul {
          address = "$private_ipv4:8500"
      }

coreos:
  etcd2:
    name: __NAME__
    listen-client-urls: http://0.0.0.0:2379,http://0.0.0.0:4001
    advertise-client-urls: http://0.0.0.0:2379,http://0.0.0.0:4001
    initial-cluster: __ETCD_SEED_CLUSTER__
    proxy: on
  units:
    - name: rpcbind.service
      enable: true
      command: start
    - name: rpc-statd.service
      enable: true
      command: start
    - name: docker.service
      command: start
      drop-ins:
        - name: "50-docker-dns.conf"
          content: |
            [Service]
            Environment=DOCKER_OPTS='--dns="$private_ipv4"'
        - name: 51-docker-mirror.conf
        - __PROXY_LINE__name: http-proxy.conf
          __PROXY_LINE__content: |
            __PROXY_LINE__[Service]
            __PROXY_LINE__EnvironmentFile=/etc/environment
    - name: consul-read-members.service
      command: start
      content: |
        [Unit]
        Description=Generates /tmp/consul_members file
        After=etcd2.service
        Requires=etcd2.service
        [Service]
        Type=oneshot
        ExecStart=/usr/bin/sh -c '/usr/bin/etcdctl ls /consul.io/members |    \
                 xargs -I {} /usr/bin/etcdctl get {} | sed s/^/"-join "/ |    \
                 tr "\n" " " > /tmp/consul_members'
    - name: consul-discovery.service
      command: start
      content: |
        [Unit]
        Description=Consul member discovery
        Requires=consul-read-members.service
        After=consul-read-members.service
        [Service]
        EnvironmentFile=/etc/environment
        ExecStart=/bin/sh -c "while true; do etcdctl set /consul.io/members/consul-${COREOS_PRIVATE_IPV4} ${COREOS_PRIVATE_IPV4} --ttl 60; sleep 30; done"
        ExecStop=/usr/bin/etcdctl rm /consul.io/members/consul-${COREOS_PRIVATE_IPV4}
    - name: consul.service
      command: start
      content: |
        [Unit]
        Description=Download and run Consul for Nomad service discovery
        Requires=consul-discovery.service
        After=consul-discovery.service
        [Service]
        EnvironmentFile=/etc/environment
        ExecStartPre=-/usr/bin/rm -rf /opt/bin
        ExecStartPre=/usr/bin/mkdir -p /opt/bin
        ExecStartPre=/usr/bin/wget -P /tmp https://releases.hashicorp.com/consul/__CONSUL_VERSION__/consul___CONSUL_VERSION___linux_amd64.zip
        ExecStartPre=/usr/bin/unzip -o /tmp/consul___CONSUL_VERSION___linux_amd64.zip -d /opt/bin
        ExecStartPre=/usr/bin/rm -f /tmp/consul___CONSUL_VERSION___linux_amd64.zip
        ExecStartPre=/usr/bin/chmod +x /opt/bin/consul
        ExecStartPre=/usr/bin/mkdir -p /var/lib/consul/data
        ExecStart=/bin/sh -c '/opt/bin/consul    \
            agent                                \
            -bind ${COREOS_PRIVATE_IPV4}         \
            -config-file /etc/consul/consul.json        \
            $(/usr/bin/cat /tmp/consul_members)'
    - name: nomad.service
      command: start
      content: |
        [Unit]
        Description=Download and run Nomad
        Requires=consul.service
        After=consul.service
        ConditionPathExists=/etc/nomad/client.hcl
        [Service]
        EnvironmentFile=/etc/environment
        ExecStartPre=/usr/bin/wget -P /tmp https://releases.hashicorp.com/nomad/__NOMAD_VERSION__/nomad___NOMAD_VERSION___linux_amd64.zip
        ExecStartPre=/usr/bin/unzip -o /tmp/nomad___NOMAD_VERSION___linux_amd64.zip -d /opt/bin
        ExecStartPre=/usr/bin/rm -f /tmp/nomad___NOMAD_VERSION___linux_amd64.zip
        ExecStartPre=/usr/bin/chmod +x /opt/bin/nomad
        ExecStartPre=/bin/sh -xc 'iface=$(ip -o -4 route get __MASTER_IP__ | awk "{print \$3}"); sed -e "s|network_interface.*|network_interface = \\"$iface\\"|" -i /etc/nomad/client.hcl'
        ExecStart=/opt/bin/nomad agent -config /etc/nomad/client.hcl
  update:
    group: __CHANNEL__
    reboot-strategy: off
