kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: test-oauth
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 9080
        hostPort: 9080
        protocol: TCP
      - containerPort: 9443
        hostPort: 9443
        protocol: TCP
