---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: playground-ca
  namespace: cert-manager
  labels:
    flypenguin.de/name: tls-cert-ingress-test
spec:
  secretName: tls-me-traefik-localhost

  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048

  usages:
    - server auth

  emailAddresses:
    - penguin@flypenguin.eu
  subject:
    organizations:
      - OAuth Test Playground

  dnsNames:
    - localhost.traefik.me
    - "*.localhost.traefik.me"

  issuerRef:
    name: playground-ca
    kind: ClusterIssuer
