#!/usr/bin/env bash

# the ImageName must be last - because it contains dots.
# image id does not (hopefully). this way we can "re-connect
# the dots" and get back the full image name, including host
# name part at the end.

# the image "me.with.dots/busy/box:boo" is a simple busybox,
# just tagged differently. I want to have the image name 
# available in elastic, so I needed to test whether this is
# actually possible.

set -e

GREP="a.b:1/my/logimage"
INAME="${GREP}:ho"
CNAME="mylogimage"

if ! docker images | grep  "$GREP" ; then
    docker pull busybox
    docker tag busybox "$INAME"
fi

if ! docker ps -a | grep -q "$CNAME" ; then
    docker run -ti \
        --log-driver=fluentd \
        --log-opt tag="c11hdocker.{{.ImageFullID}}.{{.ImageName}}" \
        --name "$CNAME" \
        "$INAME"
else
    docker start -i "$CNAME"
fi
