#!/usr/bin/env bash

echo "Please don't use this."
echo "Please use docker-compose up."

exit

docker run \
  --rm -ti \
  -p 9200:9200 -p 9300:9300 \
  -e ES_JAVA_OPTS="-Xmx256m -Xms256m" \
  -v $(pwd)/docker_elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml \
  docker.elastic.co/elasticsearch/elasticsearch:5.4.1
