---
ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.entryPoints: "websecure"
    traefik.ingress.kubernetes.io/router.middlewares: "traefik-oidc@kubernetescrd"
    traefik.ingress.kubernetes.io/router.tls: "true"
  hosts:
    - host: flyp.localhost.traefik.me
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
