---
##:CHART cert-manager/cert-manager
##:REPO cert-manager https://charts.jetstack.io

crds:
  # non-default, see https://is.gd/yLE0Dy
  enabled: true
  # non-default, see https://is.gd/Bk3hJH
  keep: false
  # non-default, see https://is.gd/m1qYKE

enableCertificateOwnerRef: true
# set "advanced" configs - see here: https://is.gd/socRJF
#config: {...}

# auto-handle all ingress certificates.
ingressShim:
  defaultIssuerName: internal-ca
  defaultIssuerKind: ClusterIssuer
  defaultIssuerGroup: cert-manager.io

prometheus:
  enabled: false
