---
rbac:
  enabled: true

ingress:
  enabled: true
  # annotations: { cert-manager.io/cluster-issuer: playground-ca }
  #certManager: true
  #tls:
  #  enabled: true
  #  secret: "tls-me-traefik-localhost-auth"
  gatewayAPI:
    enabled: false
  traefikCRD:
    enabled: false
    disableIngressRoute: false
    middlewares:
      auth:
        nameOverride: ""
        endpointOverride: ""
        authResponseHeaders:
          - "Remote-User"
          - "Remote-Name"
          - "Remote-Email"
          - "Remote-Groups"

pod:
  extraVolumes:
    - name: users-database
      secret:
        secretName: authelia-local-users-database
        optional: false
    - # to read the "email" notifications
      name: authelia-local-notifications
      emptyDir: {}

  env:
    - # https://is.gd/v9hRop
      # enabled templating ...
      name: X_AUTHELIA_CONFIG_FILTERS
      value: "template"
    - # https://is.gd/yHegFy -- authelia go templating reference
      # adds an ENV var from a secret. see "configMap.identityProviders.hmac" below.
      name: HMAC_VALUE
      valueFrom:
        secretKeyRef:
          name: authelia-local-hmac-value
          key: hmac

  extraVolumeMounts:
    - name: users-database
      mountPath: /config/users_database.yml
      readOnly: true
      subPath: users_database.yml
    - name: authelia-local-notifications
      mountPath: /authelia-notifications

  extraContainers:
    - # to read the "email" notifications
      name: filemanager
      image: filebrowser/filebrowser
      args: ["-p", "28080", "--noauth", "-r", "/authelia-notifications"]
      securityContext:
        runAsUser: 0
      ports:
        - containerPort: 28080
          name: filemanager
      volumeMounts:
        - name: authelia-local-notifications
          mountPath: /authelia-notifications

configMap:
  access_control:
    default_policy: two_factor

  authentication_backend:
    refresh_interval: always
    file:
      enabled: true
      watch: true
      search:
        email: true
        case_insensitive: false
    password_change:
      disable: false
    password_reset:
      disable: false

  identity_providers:
    # for all the secret mounting and usage see this:
    #   - https://is.gd/XeHUqZ (INCOMPLETE!)
    #   - https://is.gd/nq0PHf (full config reference)
    #   - https://is.gd/ZAxz96 (how to use secrets)
    # secrets mounted below under "secret.additionalSecrets.[...]"
    oidc:
      enabled: false
      # NO LONGER A STRING. see here: https://is.gd/zNwgrE
      # we mount that secret below. the config says "use value from '/secrets/authelia-local-hmac-value/hmac'"
      hmac_secret:
        disabled: true
        secret_name: "authelia-local-hmac-value"
        path: hmac
      jwks:
        - key_id: "authelia"
          algorithm: "RS256"
          use: "sig"
          key:
            path: /secrets/authelia-cert-private-key/tls.key
          # cert-manager certificate: https://is.gd/vLCkz7
          certificate_chain:
            path: /secrets/authelia-cert-private-key/ca.crt

      # config ref: https://is.gd/nq0PHf
      enable_client_debug_messages: false
      cors:
        # https://is.gd/F3YNB8
        allowed_origins:
          - "*" # FOR NOW

        allowed_origins_from_client_redirect_uris: false

      # https://is.gd/FhAB1j
      # copied from the terratgrunt example ...
      clients:
        - # dex ref @ authelia: https://is.gd/N8wzZP
          # dex oidc connector: ref: https://is.gd/gZdGS6
          #
          # unfortunately, not mounted, because we cannot create a pbkdf2 hash on-the-fly.
          # so ... for now.
          #
          # creating a pbkdf2 hash (from https://is.gd/YocRzt):
          #   - docker run --rm -ti authelia/authelia sh -c "authelia crypto hash generate pbkdf2"
          #
          client_name: Dex
          client_id: dex-authelia-local
          # jmkh4i7z3dh1blkqpuufkch3dtwveyjb
          client_secret: "$pbkdf2-sha512$310000$ws8vvPpgZzl0wLbQ0/VWiQ$r1Ra2ctSUhfcSjw8BgxgA3Z3uWOe6bI9HkX3hLbQtmQrsjIQA6uQfj3FiKEplnFQXNldUSBN18nkLD1FYC20Qg"
          redirect_uris:
            - https://dex.localhost.traefik.me/callback
          scopes:
            - openid
            - email
            - profile
          response_types:
            - code
          grant_types:
            - authorization_code
            - refresh_token
          access_token_signed_response_alg: "none"
          userinfo_signed_response_alg: "none"
          token_endpoint_auth_method: "client_secret_post"
          response_modes:
            - form_post
            - query
            - fragment

  notifier:
    filesystem:
      enabled: true
      filename: /authelia-notifications/notification.txt

  password_policy:
    zxcvbn:
      enabled: true
      min_score: 3

  session:
    cookies:
      - domain: localhost.traefik.me
        subdomain: auth-local

  storage:
    postgres:
      enabled: true
      deploy: true
      address: "tcp://authelia-local-postgresql.authelia-local.svc.cluster.local:5432"
      database: "authelia-local"
      schema: "public"
      username: "authelia-local"
      password:
        secret_name: ~
        value: "authelia-local"
        path: "storage.postgres.password.txt"

postgresql:
  # default values, but here to see how we configure this.
  auth:
    postgresPassword: authelia-local
    username: authelia-local
    password: authelia-local
    database: authelia-local

secret:
  additionalSecrets:
    authelia-local-hmac-value:
      path: ""
      items:
        - key: hmac
    authelia-local-cert-private-key:
      path: ""
      items:
        # https://is.gd/vLCkz7
        - key: ca.crt
        - key: tls.crt
        - key: tls.key
