---
rbac:
  enabled: true

ingress:
  enabled: true
  # cert-manager doing its magic, using an internal self-signed ca.

pod:
  extraVolumes:
    - name: users-database
      secret:
        secretName: authelia-local-users-database
        optional: false
    - name: pre-processed-config-values
      emptyDir: {}
    - # to read the "email" notifications
      name: authelia-local-notifications
      emptyDir: {}

  env:
    - # https://is.gd/v9hRop
      # enabled templating ...
      name: X_AUTHELIA_CONFIG_FILTERS
      value: "template"

  extraVolumeMounts:
    - name: users-database
      mountPath: /config/users_database.yml
      readOnly: true
      subPath: users_database.yml
    - name: authelia-local-notifications
      mountPath: /authelia-notifications
    - name: pre-processed-config-values
      mountPath: /ppc

  initContainers:
    - name: pbkdf2-hasher
      image: ghcr.io/authelia/authelia
      command:
        - sh
        - -c
        - |
          set -euo pipefail
          CS=/ppc/client-secrets
          mkdir $CS
          cd $CS
          echo "Password SHA256: $(echo "$CLIENT_SECRET" | sha256sum)"
          authelia crypto hash generate --password "$CLIENT_SECRET" | sed -E "s/^([^ ]+ )?//" > dex-authelia-local
          authelia crypto hash validate --password "$CLIENT_SECRET" -- "$(cat dex-authelia-local)"
          echo "Validation successful."

      env:
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: authelia-local-client-secret-dex
              key: client_secret
      volumeMounts:
        - name: pre-processed-config-values
          mountPath: /ppc

  extraContainers:
    - # to read the "email" notifications
      name: filemanager
      image: filebrowser/filebrowser
      args: ["-p", "28080", "--noauth", "-r", "/authelia-notifications"]
      securityContext:
        runAsUser: 0
      ports:
        - containerPort: 28080
          name: filemanager
      volumeMounts:
        - name: authelia-local-notifications
          mountPath: /authelia-notifications

configMap:
  access_control:
    default_policy: two_factor

  authentication_backend:
    refresh_interval: always
    file:
      enabled: true
      watch: true
      search:
        email: true
        case_insensitive: false
    password_change:
      disable: false
    password_reset:
      disable: false

  identity_providers:
    # for all the secret mounting and usage see this:
    #   - https://is.gd/XeHUqZ (INCOMPLETE!)
    #   - https://is.gd/nq0PHf (full config reference)
    #   - https://is.gd/ZAxz96 (how to use secrets)
    # secrets mounted below under "secret.additionalSecrets.[...]"
    oidc:
      enabled: true
      # NO LONGER A STRING. see here: https://is.gd/zNwgrE
      # we mount that secret below. the config says "use value from '/secrets/authelia-local-hmac-value/hmac'"
      hmac_secret:
        disabled: true
        secret_name: "authelia-local-hmac-value"
        path: hmac
      jwks:
        - key_id: "authelia"
          algorithm: "RS256"
          use: "sig"
          key:
            path: /secrets/authelia-local-cert-private-key/tls.key
          # cert-manager certificate: https://is.gd/vLCkz7
          certificate_chain:
            path: /secrets/authelia-local-cert-private-key/tls.crt

      # config ref: https://is.gd/nq0PHf
      enable_client_debug_messages: false
      cors:
        # https://is.gd/F3YNB8
        allowed_origins:
          - "*" # FOR NOW

        allowed_origins_from_client_redirect_uris: false

      # https://is.gd/FhAB1j
      # copied from the terratgrunt example ...
      clients:
        - # dex ref @ authelia: https://is.gd/N8wzZP
          # dex oidc connector: ref: https://is.gd/gZdGS6
          # we create the pbkdf2 hash from the init container - see above.
          client_name: Dex
          client_id: dex-authelia-local
          client_secret:
            path: /ppc/client-secrets/dex-authelia-local
          redirect_uris:
            - https://dex.localhost.traefik.me/callback
          scopes:
            - openid
            - email
            - profile
          response_types:
            - code
          grant_types:
            - authorization_code
            # - refresh_token # Authelia warning: "refresh_token" _WITH_ "offline_access", or none.
          access_token_signed_response_alg: "none"
          userinfo_signed_response_alg: "none"
          token_endpoint_auth_method: "client_secret_post"
          response_modes:
            - form_post
            - query
            - fragment

  notifier:
    filesystem:
      enabled: true
      filename: /authelia-notifications/notification.txt

  password_policy:
    zxcvbn:
      enabled: true
      min_score: 3

  session:
    cookies:
      - domain: localhost.traefik.me
        subdomain: auth-local

  storage:
    postgres:
      enabled: true
      deploy: true
      address: "tcp://authelia-local-postgresql.authelia-local.svc.cluster.local:5432"
      database: "authelia-local"
      schema: "public"
      username: "authelia-local"
      password:
        secret_name: ~
        value: "authelia-local"
        path: "storage.postgres.password.txt"

postgresql:
  # default values, but here to see how we configure this.
  auth:
    postgresPassword: authelia-local
    username: authelia-local
    password: authelia-local
    database: authelia-local

secret:
  additionalSecrets:
    authelia-local-client-secret-dex:
      path: ""
      items:
        - key: client_secret
    authelia-local-hmac-value:
      path: ""
      items:
        - key: hmac
    authelia-local-cert-private-key:
      path: ""
      items:
        # https://is.gd/vLCkz7
        - key: ca.crt
        - key: tls.crt
        - key: tls.key
