---
##:CHART dex/dex
##:REPO dex https://charts.dexidp.io

replicaCount: 1
namespaceOverride: "dex"
hostAliases: []
https:
  enabled: false

configSecret:
  create: true
  # name: ""

config:
  # config examples:
  #   - dev config: https://is.gd/pijoRf
  #   - AD connect: https://is.gd/AjKFns

  # required, but weirdly nowhere documented ...
  issuer: https://dex.localhost.traefik.me

  # required
  storage:
    type: kubernetes
    config:
      inCluster: true

  # naturally, required ...
  connectors:
    - type: oidc
      id: authelia-local
      name: Externe Nutzer
      config:
        issuer: http://authelia-local.authelia-local.svc.cluster.local

        # Connector config values starting with a "$" will read from the environment.
        clientID: dex
        clientSecret: $CLIENT_SECRET_AUTHELIA_LOCAL

        # Dex's issuer URL + "/callback"
        redirectURI: https://dex.localhost.traefik.me/callback

        # Default is profile and email, full list at https://dexidp.io/docs/custom-scopes-claims-clients/
        # scopes: [profile, email, groups]

        # Don't insist on verified email addresses
        # insecureSkipEmailVerified: true

        # if true, the connector will query the UserInfo endpoint for additional claims.
        # https://openid.net/specs/openid-connect-core-1_0.html#UserInfo
        # getUserInfo: true

        # The set claim is used as user id. Default: "sub", list at https://openid.net/specs/openid-connect-core-1_0.html#Claims
        # userIDKey: nickname

        # The set claim is used as user name. Default: "name"
        # userNameKey: nickname

        # Map non-standard claims returned by provicers. https://openid.net/specs/openid-connect-core-1_0.html#Claims
        claimMapping:
          # The set claim is used as preferred username.
          # Default: preferred_username
          # preferred_username: other_user_name
    - type: oidc
      id: authelia-ldap
      name: LDAP Nutzer (Windows)
      config:
        issuer: http://authelia-ldap.authelia-ldap.svc.cluster.local
        clientID: dex
        clientSecret: $CLIENT_SECRET_AUTHELIA_LDAP
        redirectURI: https://dex.localhost.traefik.me/callback

envVars:
  - name: CLIENT_SECRET_AUTHELIA_LOCAL
    valueFrom:
      secretKeyRef:
        name: dex-client-secret-authelia-local
        key: client_secret
  - name: CLIENT_SECRET_AUTHELIA_LDAP
    valueFrom:
      secretKeyRef:
        name: dex-client-secret-authelia-ldap
        key: client_secret

ingress:
  enabled: true
  # className: ""
  # annotations: {}
  hosts:
    - host: dex.localhost.traefik.me
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

networkPolicy:
  enabled: false

service:
  type: ClusterIP
  ports:
    http:
      port: 5556
    https:
      port: 5554

serviceMonitor:
  enabled: false

# see example config file "config.yaml.dist": https://is.gd/MY10DS
staticClients:
  - id: traefik-oidc
    redirectURIs:
      - ...
    name: Traefik OIDC authentication
    secret: qem80y5no10g7qpz5h0nhjym0j9hawh8qod70ez1ufkjrb2gz3ye455mj8fkrzhc
