#!/usr/bin/env bash

echo "Please don't use this."
echo "Please use docker-compose up."

exit

docker run \
  --rm -ti \
  -p "5601:5601" \
  -v $(pwd)/docker_kibana/config/:/usr/share/kibana/config \
  docker.elastic.co/kibana/kibana:5.4.1
